services:
  ocis:
    container_name: ocis
    image: owncloud/ocis:7.2
    restart: always
    ports:
      - ${PORT}:9200
    logging:
      driver: local
    environment:
      - PROXY_TLS=false
      - OCIS_INSECURE=true
      - OCIS_URL=${OCIS_URL}
      - OCIS_LOG_LEVEL=WARN
      - OCIS_LOG_COLOR=true
      - OCIS_LOG_PRETTY=true
      - IDM_ADMIN_PASSWORD=${IDM_ADMIN_PASSWORD}
    volumes:
      - ${CONFIG_DIR}:/etc/ocis
      - ocis_data:/var/lib/ocis
      - ${APPS_DIR}:/var/lib/ocis/web/assets/apps

volumes:
  ocis_data:
    external: true